### ISSUE TITLE
Update document number on Overview page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-swecommon20#11]
![Screenshot 2020-06-23 at 12 11 43](https://user-images.githubusercontent.com/18121038/85397154-f7ee0500-b54a-11ea-92be-f6ce34c13513.png)

**Comment by dstenger** [comment]
Document number was updated: https://github.com/opengeospatial/ets-swecommon20/commit/b077444bf5567d9465c6903daa8999d5828a6d51
