### ISSUE TITLE
Create unit tests for each test

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-swecommon20#12]
Currently, there are no unit tests implemented: https://github.com/opengeospatial/ets-swecommon20/tree/master/src/test/java/org/opengis/cite/swecommon20

**Comment by ghobona** [comment]
Agreement on 2020-07-01 that @arieslai will modify the doTestRun() unit test at https://github.com/opengeospatial/ets-swecommon20/blob/master/src/test/java/org/opengis/cite/swecommon20/VerifyTestNGController.java#L54

**Comment by ghobona** [comment]
Update on 2020-07-15 @arieslai has uncommented the code and has been able to run the sample SWE Common test file successfully. 

Agreement that @arieslai will create a pull request and @ghobona will review.

**Comment by arieslai** [comment]
Dear @ghobona ,

The pull request is made, thank you.
https://github.com/opengeospatial/ets-swecommon20/pull/13

**Comment by dstenger** [comment]
@arieslai Can you please check if command `mvn clean install site -Pintegration-tests,docker` returns a successful build?

**Comment by arieslai** [comment]
The build was successful.
