### ISSUE TITLE
Unable to test documents retrieved from URL

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-swecommon20#15]
I tried these URLs and still got the "Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.swecommon20.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: javax/ws/rs/client/ClientBuilder
Result: Failed" error.

https://raw.githubusercontent.com/opengeospatial/ets-swecommon20/master/src/test/resources/examples/52NorthSWECom.xml

http://schemas.opengis.net/sweCommon/2.0/examples/image_data.xml

http://schemas.opengis.net/sweCommon/2.0/examples/weather_data.xml

However, the error does not occur when uploading the files.

**Comment by dstenger** [comment]
@arieslai If the duplicate jersey dependency causes the problem, can you please try to upgrade the complete project to jersey 2?

**Comment by dstenger** [comment]
@arieslai Can you please also check if you can fix this issue by using jersey 1?

**Comment by dstenger** [comment]
Following commit updated Jersey-Client 1 to Jersey-Client 2 and probably caused the problem: https://github.com/opengeospatial/ets-swecommon20/commit/a38eb47ef5b7e157c948247d506067a9e24ab01a

**Comment by dstenger** [comment]
It seems that this test suite is the only test suite using `org.glassfish.jersey.core:jersey-client`.
https://github.com/search?q=org%3Aopengeospatial+%22org.glassfish.jersey.core%22&type=Code

Thus, I propose to downgrade to Jersey-Client 1 again.

**Comment by dstenger** [comment]
@arieslai Can you please test pull request #18?
