### ISSUE TITLE
Test suite passes successfully against non SWECommon files

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-swecommon20#16]
If a non SWECommon file, e.g. any GML file, is uploaded to the test suite, it passes the Basic Conformance classes.

**Comment by dstenger** [comment]
First, we will concentrate on tests in class `CoreConcept`.

**Comment by dstenger** [comment]
There is a bug in method `org.opengis.cite.swecommon20.level1.CoreConcept#Core`.

Instead of validating against the SWECommon schema, the schemas referenced in the tested file are used for schema validation.

In addition, in https://github.com/opengeospatial/ets-swecommon20/blob/4ce5033c049e50d2447a600a7710e6dd7066862d/src/main/java/org/opengis/cite/swecommon20/level1/CoreConcept.java#L24 the schema-catalog.xml must be passed instead of the SWECommon schema. However, this does not lead to the error but makes the test inefficient.

**Comment by dstenger** [comment]
Fix was implemented and enables validation against the schema placed in the test suite.
Relevant commit: https://github.com/opengeospatial/ets-swecommon20/pull/17/commits/4dfba36a6d5fa96968e65467011bf7a75b64ad3c

However, example file 52NorthSWECom.xml does not pass the schema validation now (see adjusted test in commit).
On the other hand, example files nav_data.xml and weather_data.xml pass the schema validation successfully.

@ghobona @arieslai Can you please review the fix?

**Comment by ghobona** [comment]
Fixed by PR https://github.com/opengeospatial/ets-swecommon20/pull/17
