### ISSUE TITLE
Improve name of test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-swecommon20#3]
Currently, "Test suite: ets-swecommon20" is displayed as name of test suite on http://cite.opengeospatial.org/te2/.

The name should be the name of the specification instead (see other test suites).

**Comment by lgoltz** [comment]
Proposals:
 * Sensor Web Enablement (SWE) Common Data Model Encoding Standard
 * SWE Common Data Model Encoding Standard

**Comment by epicureanism** [comment]
SWE Common Data Model Encoding Standard was accepted and modified. 2478a6c
