### ISSUE TITLE
Add conformance class configuration into the ets-swecommon20 test

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-swecommon20#4]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
Basic conformance classes are already configured: https://github.com/opengeospatial/ets-swecommon20/blob/fcb3434ab853494d546c40826fb1bd00d5157724/src/main/config/teamengine/config.xml#L16-L18

But the name does not match the test names in the testng.xml: https://github.com/opengeospatial/ets-swecommon20/blob/master/src/main/resources/org/opengis/cite/swecommon20/testng.xml

**Comment by lgoltz** [comment]
@epicureanism Can you help us here? Which are the basic conformance classes? If it is only CoreConcept the testng.xml must be adapted.

**Comment by epicureanism** [comment]
We've udpated the conformance class settings in both testng.xml and config.xml , but not quite sure this setting is correct or not, it would be appreciated if anyone can help make sure the settings are in the right place, thx
 2b9e33320af2419e119dc5376db3aa5da869b0d2

**Comment by dstenger** [comment]
@keshav-nangare Can you please test if the update of epicureanism works?

**Comment by keshavnangare** [comment]
@epicureanism 

Can you please provide service to test this implementation?

**Comment by epicureanism** [comment]
@keshav-nangare  
Do you mean teamengine service? 
If so, we tried to build with teamengine docker, but still have problem to build the docker image.
Still working on this.

**Comment by keshavnangare** [comment]
@epicureanism 

Yes. We need Reference Implementation of this test-suite to test the changes.

**Comment by dstenger** [comment]
@epicureanism 
If you need any help with TEAM Engine on Docker, you can create an issue in [teamengine-docker](https://github.com/opengeospatial/teamengine-docker) or use the mailing list for questions.

**Comment by keshavnangare** [comment]
@epicureanism 

It would be great if you provide Reference Implementation for this test, so I can test this changes.

**Comment by dstenger** [comment]
testng.xml was adjusted: https://github.com/opengeospatial/ets-swecommon20/commit/74bb10e07eae7b185d0b8db1257f29ee3daf04ba

**Comment by dstenger** [comment]
Test with [1] was successful. New report is displayed.

[1] https://raw.githubusercontent.com/opengeospatial/ets-swecommon20/master/src/test/resources/examples/spec/simple_components.xml
