### ISSUE TITLE
Update dependency org.opengis.cite:schema-utils to version 1.8

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-swecommon20#8]
Dependency org.opengis.cite:schema-utils must be updated to version 1.8.

Current version 1.5 of this library creates a dependency conflict with other test suites (e.g. WFS 2.0) causing that there are always some broken tests in one of those tests suites (e.g. on http://cite.opengeospatial.org/te2/).

Currently, several WFS 2.0 tests are failing on Beta environment because of this conflict (issue: https://github.com/opengeospatial/ets-wfs20/issues/153).

**Comment by dstenger** [comment]
Currently, because of the conflict, some SWE Common tests fail on Beta environment.
WFS 2.0 test suite was fixed on Beta (https://github.com/opengeospatial/ets-wfs20/issues/153).

**Comment by dstenger** [comment]
@epicureanism Can you please take a look at this problem?

**Comment by epicureanism** [comment]
issue fixed in https://github.com/opengeospatial/ets-swecommon20/commit/a38eb47ef5b7e157c948247d506067a9e24ab01a
@dstenger can you help to pull the latest codes and test in the beta environment again?
